src/Entity/Plant.php
<?php

namespace App\Entity;

use App\Repository\PlantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlantRepository::class)]
class Plant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $level = null;

    #[ORM\Column]
    private ?bool $isShow = null;

    #[ORM\OneToOne(inversedBy: 'idPlant', cascade: ['persist', 'remove'])]
    private ?Image $idImage = null;

    #[ORM\OneToMany(mappedBy: 'plant', targetEntity: Find::class)]
    private Collection $idplant;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_after = null;

    public function __construct()
    {
        $this->idplant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function __toString() { return $this->name;}
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function isIsShow(): ?bool
    {
        return $this->isShow;
    }

    public function setIsShow(bool $isShow): self
    {
        $this->isShow = $isShow;

        return $this;
    }

    public function getIdImage(): ?Image
    {
        return $this->idImage;
    }

    public function setIdImage(?Image $idImage): self
    {
        $this->idImage = $idImage;

        return $this;
    }

    /**
     * @return Collection<int, Find>
     */
    public function getIdplant(): Collection
    {
        return $this->idplant;
    }

    public function addIdplant(Find $idplant): self
    {
        if (!$this->idplant->contains($idplant)) {
            $this->idplant->add($idplant);
            $idplant->setPlant($this);
        }

        return $this;
    }

    public function removeIdplant(Find $idplant): self
    {
        if ($this->idplant->removeElement($idplant)) {
            // set the owning side to null (unless already changed)
            if ($idplant->getPlant() === $this) {
                $idplant->setPlant(null);
            }
        }

        return $this;
    }

    public function getDescriptionAfter(): ?string
    {
        return $this->description_after;
    }

    public function setDescriptionAfter(string $description_after): self
    {
        $this->description_after = $description_after;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;
use App\Repository\PlantRepository;
use App\Repository\UserRepository;
use App\Repository\FindRepository;
use App\Repository\ImageRepository;
use App\Entity\Plant;
use App\Entity\Find;
use App\Entity\User;
use App\Form\FindType;
use App\Form\PlantType;
use App\Form\EditProfilType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\PlantController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/home')]
class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    #[Route('/play', name: 'app_play')]
    public function play(Request $request ,PlantRepository $plantRepository,UserRepository $userrepository, EntityManagerInterface $em): Response
    {
        $find = new Find();
        // $this->find->setUrl($find);
        $form = $this->createForm(FindType::class, $find);
        $form->handleRequest($request);
        // $user= $userrepository->find($_POST['user']);
        // $plant = $plantrepository->find($_POST['plant']);
        
        if ($form->isSubmitted()&& $form->isValid()){
            $find = $form->getData();
            
            //move le fichier
            // recuperer son nom
            // $filename=$user->getName().'_'.$plant->getName().'.png';
            // $find->setUrl($filename);
            // $lat = addslashes($_POST['lat']);
            // $lng = addslashes($_POST['lng']);
            // $find->setLatitude($latitude);
            // $find->setLongitude($longitude);
            $em->persist($find);
            $em->flush();
            echo 'Ajout réussi';
            return $this->render('home/playafter.html.twig', [
                'plants' => $plantRepository->findBy(array('level'=>'1'),array('id'=>'desc'),1), # TODO : Please remove the level = 1
            ]);
        }
        return $this->render('home/play.html.twig', [
            'plants' => $plantRepository->findBy(array('level'=>'1'),array('id'=>'desc'),1),
            'form' => $form->createView()
        ]);
    }

    #[Route('/profil', name: 'app_profil')]
    public function profil(): Response
    {
        return $this->render('home/profil.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/profil/edit', name: 'app_profil_edit')]
    public function editProfil(Request $request, ManagerRegistry $doctrine, UserPasswordHasherInterface $userPasswordHasher):Response
    {
        $user = $this->getUser();
        $form = $this->createForm(EditProfilType::class, $user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('ModifPassword')->getData()
                )
            );
            $em = $doctrine->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash("message", "profil mis à jour");
            return $this->redirectToRoute('app_profil');
        }

        return $this->render('home/editprofil.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/profil/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        $session = new Session();
        $session->invalidate();

        return $this->redirectToRoute('app_register', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/stats', name: 'app_stats')]
    public function stats(FindRepository $findRepository, PlantRepository $plantRepository ): Response
    {
        $plants = $plantRepository->findAll();
        $finds = $findRepository->findAll();
        return $this->render('home/stats.html.twig', [
            'controller_name' => 'HomeController',
            'finds' => $finds,
            'plants' => $plants,
        ]);
    }

    #[Route('/stats/{id}', name: 'app_plant_show', methods: ['GET'])]
    public function show(Plant $plant): Response
    {
        return $this->render('home/showplant.html.twig', [
            'plant' => $plant,
        ]);
    }
}

templates/home/_delete_form.html.twig
<form class="w-137px" method="post" action="{{ path('app_user_delete', {'id': app.user.id}) }}" onsubmit="êtes-vous sûr de vouloir supprimer votre compte ?">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ app.user.id) }}">
    <button class="b-log">Me désinscrire</button>
</form>

templates/home/editprofil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifiez le profil !{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/styles/profil-page.css') }}" />
{% endblock %}

{% block body %}
<body>
    <main class="disp-f j-c-c al-c w-100pc h-100vh">
        <div class="disp-f j-c-c bg-c-white card-s al-c">
            <div class="disp-f al-c j-c-c f-d-c w-50pc h-100pc">
                {{ form_start(form) }}
                    {{ form_row(form.avatar, {label: 'Avatar: '}) }}
                    {{ form_row(form.email, {label: 'Email: '}) }}
                    {{ form_row(form.ModifPassword, {label: 'Mot de passe:'}) }}
                    <button class="b-log w-400px" type="submit" class="btn">Modifier son compte</button>
                {{ form_end(form) }}
                <a href="{{ path('app_profil') }}">profil</a>
            </div>
        </div>
    </main>
</body>

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bienvenue sur Cherche et Trouve</h1>

    <ul>
        <a href="{{ path('app_play') }}">Jouer</a>
        <a href="{{ path('app_stats') }}">Statistiques</a>
        <a href="{{ path('app_profil') }}">Profil</a>
    </ul>
</div>
{% endblock %}

templates/home/play.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bonjour j'espère que tu es prêt à chercher </h1>
    <p> Voici la description de la plante à trouver </p>
    {% for plant in plants %}
    <tr>
        <br>
        <td>{{ plant.name}}</td>
        <br>
        <td>{{ plant.description }}</td>
        <br>
    </tr>
    <img class="image" src="{{ asset('assets/medias/pissenlit.jpg') }}"></img>
    {% endfor %}
    
    <video id="video" width="640" height="480" autoplay></video>
    <button id="snap">Take Photo</button>
    <canvas id="canvas" width="640" height="480"></canvas>
    {{ form_start(form) }}
    <button type="submit" class="btn btn-succes">Valider photo</button>
    {{ form_end(form) }}
</div>

<button onclick="window.location.href='/home';"> Home</button>
<script src="https://raw.githubusercontent.com/exif-js/exif-js/master/exif.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>



{% endblock %}

    {% block javascripts %}
        <script type="text/javascript" src="{{ asset('assets/js/pic.js') }}"></script>
        <script type="text/javascript" src="{{ asset('assets/js/getloc.js') }}"></script>
    {% endblock %}

templates/home/playafter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bonjour j'espère que tu es prêt à chercher </h1>
    <p> Voici la description de la plante à trouver </p>
    {% for plant in plants %}
    <tr>
        <br>
        <td>{{ plant.name}}</td>
        <br>
        <td><p class="after">{{ plant.DescriptionAfter }}</p></td>
    </tr>
    <img class="image" src="{{ asset('assets/medias/pissenlit.jpg') }}"></img>
    {% endfor %}
    
</div>
<button onclick="window.location.href='/home';"> Home</button>


{% endblock %}

    {% block javascripts %}
        <script type="text/javascript" src="{{ asset('assets/js/pic.js') }}"></script>
    {% endblock %}

templates/home/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voici votre profil !{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/styles/profil-page.css') }}" />
{% endblock %}

{% block body %}
<body>
    <main class="disp-f j-c-c al-c w-100pc h-100vh">
        <div class="disp-f j-c-c bg-c-white card-s al-c">
            <div class="disp-f al-c j-c-c f-d-c w-50pc h-100pc">
                <h1>Bienvenue sur votre profil !</h1>
                <p>Vous avez trouvé N plantes</p>
                <img src="{{ asset(app.user.avatar) }}" alt="a child with flowers" width="150" height="200">
                <div class="l-h">Email: {{ app.user.email }}</div>
                <div class="l-h">Points d'expérience: {{ app.user.exp | default("0") }}</div>
                <div class="w-400px disp-f j-c-c gap-20px">
                    <a class="b-reg" href="{{ path('app_profil_edit') }}">Modifier mon profil</a>
                    {{ include('home/_delete_form.html.twig') }}
                </div>
                <div class="disp-f j-c-c w-90pc mg-t-5vh">
                    <a class="b-reg" href="{{ path('app_home') }}">Home</a>
                </div>
            </div>
        </div>
    </main>
</body>
{% endblock %}

templates/home/showplant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plant{% endblock %}

{% block body %}
    <h1>Plant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ plant.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ plant.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ plant.description }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ plant.level }}</td>
            </tr>
            <tr>
                <th>IsShow</th>
                <td>{{ plant.isShow ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Description_after</th>
                <td>{{ plant.descriptionAfter }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_stats') }}">back to list</a>

{% endblock %}

templates/home/stats.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visionnez vos statistiques !{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
    <link rel="stylesheet" href="{{ asset('assets/styles/stats.css') }}" />
{% endblock %}

{% block body %}
    {% for find in finds %}
        {% if app.user.id == find.user.id %}
            {% for plant in plants %}
                {% if plant.id == find.plant.id %}
                        <a href=stats/{{ plant.id }}><img src="{{ asset(plant.idImage.url) }}" alt="a child with flowers" width="50" height="50"></a>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
    <div id="map"></div>
{% endblock %}

{% block javascripts %}
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script>
        var map = L.map('map').setView([48.1113387, -1.6800198], 12);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        {% for find in finds %}
            {% if app.user.id == find.user.id %}
                L.marker([{{ find.latitude }}, {{ find.longitude }}]).addTo(map)
                    .bindPopup('Rennes, Ille-et-Villaine, France<br>Voici une plante trouvée');
            {% endif %}
        {% endfor %}
    </script>
    
{% endblock %}